/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    50: 'rgb(var(--color-primary-50) / <alpha-value>)',
                    100: 'rgb(var(--color-primary-100) / <alpha-value>)',
                    200: 'rgb(var(--color-primary-200) / <alpha-value>)',
                    300: 'rgb(var(--color-primary-300) / <alpha-value>)',
                    400: 'rgb(var(--color-primary-400) / <alpha-value>)',
                    500: 'rgb(var(--color-primary-500) / <alpha-value>)',
                    600: 'rgb(var(--color-primary-600) / <alpha-value>)',
                    700: 'rgb(var(--color-primary-700) / <alpha-value>)',
                    800: 'rgb(var(--color-primary-800) / <alpha-value>)',
                    900: 'rgb(var(--color-primary-900) / <alpha-value>)',
                    950: 'rgb(var(--color-primary-950) / <alpha-value>)',
                },
                secondary: {
                    50: 'rgb(var(--color-secondary-50) / <alpha-value>)',
                    100: 'rgb(var(--color-secondary-100) / <alpha-value>)',
                    200: 'rgb(var(--color-secondary-200) / <alpha-value>)',
                    300: 'rgb(var(--color-secondary-300) / <alpha-value>)',
                    400: 'rgb(var(--color-secondary-400) / <alpha-value>)',
                    500: 'rgb(var(--color-secondary-500) / <alpha-value>)',
                    600: 'rgb(var(--color-secondary-600) / <alpha-value>)',
                    700: 'rgb(var(--color-secondary-700) / <alpha-value>)',
                    800: 'rgb(var(--color-secondary-800) / <alpha-value>)',
                    900: 'rgb(var(--color-secondary-900) / <alpha-value>)',
                    950: 'rgb(var(--color-secondary-950) / <alpha-value>)',
                },
                neutral: {
                    50: 'rgb(var(--color-neutral-50) / <alpha-value>)',
                    100: 'rgb(var(--color-neutral-100) / <alpha-value>)',
                    200: 'rgb(var(--color-neutral-200) / <alpha-value>)',
                    300: 'rgb(var(--color-neutral-300) / <alpha-value>)',
                    400: 'rgb(var(--color-neutral-400) / <alpha-value>)',
                    500: 'rgb(var(--color-neutral-500) / <alpha-value>)',
                    600: 'rgb(var(--color-neutral-600) / <alpha-value>)',
                    700: 'rgb(var(--color-neutral-700) / <alpha-value>)',
                    800: 'rgb(var(--color-neutral-800) / <alpha-value>)',
                    900: 'rgb(var(--color-neutral-900) / <alpha-value>)',
                    950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
                },
                danger: {
                    50: 'rgb(var(--color-danger-50) / <alpha-value>)',
                    100: 'rgb(var(--color-danger-100) / <alpha-value>)',
                    200: 'rgb(var(--color-danger-200) / <alpha-value>)',
                    300: 'rgb(var(--color-danger-300) / <alpha-value>)',
                    400: 'rgb(var(--color-danger-400) / <alpha-value>)',
                    500: 'rgb(var(--color-danger-500) / <alpha-value>)',
                    600: 'rgb(var(--color-danger-600) / <alpha-value>)',
                    700: 'rgb(var(--color-danger-700) / <alpha-value>)',
                    800: 'rgb(var(--color-danger-800) / <alpha-value>)',
                    900: 'rgb(var(--color-danger-900) / <alpha-value>)',
                    950: 'rgb(var(--color-danger-950) / <alpha-value>)',
                },
                warning: {
                    50: 'rgb(var(--color-warning-50) / <alpha-value>)',
                    100: 'rgb(var(--color-warning-100) / <alpha-value>)',
                    200: 'rgb(var(--color-warning-200) / <alpha-value>)',
                    300: 'rgb(var(--color-warning-300) / <alpha-value>)',
                    400: 'rgb(var(--color-warning-400) / <alpha-value>)',
                    500: 'rgb(var(--color-warning-500) / <alpha-value>)',
                    600: 'rgb(var(--color-warning-600) / <alpha-value>)',
                    700: 'rgb(var(--color-warning-700) / <alpha-value>)',
                    800: 'rgb(var(--color-warning-800) / <alpha-value>)',
                    900: 'rgb(var(--color-warning-900) / <alpha-value>)',
                    950: 'rgb(var(--color-warning-950) / <alpha-value>)',
                },
                accent: {
                    50: 'rgb(var(--color-accent-50) / <alpha-value>)',
                    100: 'rgb(var(--color-accent-100) / <alpha-value>)',
                    200: 'rgb(var(--color-accent-200) / <alpha-value>)',
                    300: 'rgb(var(--color-accent-300) / <alpha-value>)',
                    400: 'rgb(var(--color-accent-400) / <alpha-value>)',
                    500: 'rgb(var(--color-accent-500) / <alpha-value>)',
                    600: 'rgb(var(--color-accent-600) / <alpha-value>)',
                    700: 'rgb(var(--color-accent-700) / <alpha-value>)',
                    800: 'rgb(var(--color-accent-800) / <alpha-value>)',
                    900: 'rgb(var(--color-accent-900) / <alpha-value>)',
                    950: 'rgb(var(--color-accent-950) / <alpha-value>)',
                },
                tertiary: {
                    50: 'rgb(var(--color-tertiary-50) / <alpha-value>)',
                    100: 'rgb(var(--color-tertiary-100) / <alpha-value>)',
                    200: 'rgb(var(--color-tertiary-200) / <alpha-value>)',
                    300: 'rgb(var(--color-tertiary-300) / <alpha-value>)',
                    400: 'rgb(var(--color-tertiary-400) / <alpha-value>)',
                    500: 'rgb(var(--color-tertiary-500) / <alpha-value>)',
                    600: 'rgb(var(--color-tertiary-600) / <alpha-value>)',
                    700: 'rgb(var(--color-tertiary-700) / <alpha-value>)',
                    800: 'rgb(var(--color-tertiary-800) / <alpha-value>)',
                    900: 'rgb(var(--color-tertiary-900) / <alpha-value>)',
                    950: 'rgb(var(--color-tertiary-950) / <alpha-value>)',
                },
            }
        },
    },
    plugins: [],
}
